name: Access Azure Blob Container

on: 
  push:
    branches:
      - main

jobs:
  display_blob: 
    name: Display Container
    runs-on: ubuntu-latest
    steps:
      - name: Step one checkout
        uses: actions/checkout@v2
      - name: Azure CLI Action
        uses: Azure/cli@v1.0.8
        with: 
          azcliversion: 2.30.0 
          inlineScript: |
            az storage container list --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRINGS }}" --query "[].name"
            
